---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /etc/pki/CA/certs/
      - /etc/pki/CA/crl/
      - /etc/pki/CA/newcerts/
      - /etc/pki/CA/private/
      - /etc/pki/tls/certs/
      - /etc/pki/tls/private/
      - /etc/ssl/certs/
      - /etc/ssl/private/
    filterfiles_include:
      - '^/etc/pki/CA/certs/.*\.crt$'
      - '^/etc/pki/CA/crl/.*\.crt$'
      - '^/etc/pki/CA/newcerts/.*\.crt$'
      - '^/etc/pki/CA/private/.*\.key$'
      - '^/etc/pki/tls/private/.*\.key$'
      - '^/etc/pki/tls/certs/.*\.crt$'
      - '^/etc/ssl/certs/.*\.crt$'
      - '^/etc/ssl/private/.*\.pem$'
    filterfiles_exclude:
      - '^/etc/pki/tls/certs/ca-bundle\.crt$'
      - '^/etc/pki/tls/certs/ca-bundle\.trust\.crt$'
      - '^/etc/ssl/certs/ca-certificates\.crt$'
      - '^/etc/ssl/certs/.*snakeoil.*$'
      - '^/etc/ssl/private/.*snakeoil.*$'

- name: Remove CA certificates
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

