---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /etc/sysconfig/iptables
      - /etc/firewalld/services/
      - /etc/firewalld/zones/
      - /etc/ufw/applications.d/
    filterfiles_include:
      - '^/etc/sysconfig/iptables$'
      - '^/etc/firewalld/services/.*'
      - '^/etc/firewalld/zones/.*'
      - '^/etc/ufw/applications.d/.*'

- name: Remove firewall rules
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

