---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/spool/mail/
      - /var/mail/
    filterfiles_include:
      - '^/var/spool/mail/.*'
      - '^/var/mail/.*'

- name: Remove mail from the local mail spool directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

