---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/cache/
      - /var/lib/rpm/
      - /var/lib/yum/
      - /var/lib/apt/
    filterfiles_include:
      - '^/var/cache/apt/archives/.*'
      - '^/var/cache/dnf/.*'
      - '^/var/cache/yum/.*'
      - '^/var/cache/zypp.*'
      - '^/var/lib/rpm/__db\..*'
      - '^/var/lib/yum/uuid$'
      - '^/var/lib/apt/lists/.*$'
      - '^/var/lib/apt/periodic/.*$'
      - '^/var/lib/apt/mirrors/.*$'
      - '^/var/lib/apt/lists/cdrom.*$'
      - '^/var/lib/apt/lists/daily_lock.*$'
      - '^/var/lib/apt/lists/extended_states.*$'

- name: Remove package manager cache
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

