---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/run/console/
      - /var/run/faillock/
      - /var/run/sepermit/
    filterfiles_include:
      - '^/var/run/console/.*'
      - '^/var/run/faillock/.*'
      - '^/var/run/sepermit/.*'

- name: Remove PAM data
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

