---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /etc/
    filterfiles_include:
      - '^/etc/(group|gshadow|passwd|shadow|subuid|subgid)-$'

- name: Remove /etc/passwd- and similar backup files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

