---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/log/puppet/
      - /var/lib/puppet/
    filterfiles_include:
      - '^/var/(lib|log)/puppet/.*'

- name: Remove puppet data and log files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

