---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/(lib|log)/samba/
    filterfiles_include:
      - '^/var/log/samba/old/.*'
      - '^/var/(lib|log)/samba/.*'

- name: Remove Samba database and log files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

