---

- name: Filter files
  import_role:
    name: filterfiles
  vars:
    filterfiles_paths:
      - /var/log/sssd/
      - /var/lib/sss/db/
    filterfiles_include:
      - '^/var/log/sssd/.*'
      - '^/var/lib/sss/db/.*'

- name: Remove sssd database and log files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ filterfiles_files }}"

# vim:ft=ansible:et:ts=2:sw=2:sts=2:

